# Generated by Django 4.0 on 2025-02-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_parent_user_alter_student_user'),
        ('achievements', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-date_achieved']},
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='school_name',
        ),
        migrations.AddField(
            model_name='achievement',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='users.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='users.student'),
        ),
    ]
